---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: ${SERVICE_API_REPO}
  triggers:
  - type: commit
  properties:
  jobs:
  - name: Package
    type: builder
    working_dir: 
    artifact_dir: target
    build_type: maven
    script: |-
      #!/bin/bash
      export JAVA_HOME=$JAVA8_HOME
      
      mvn -B package
